[book]
authors = ["eunomia-bpf"]
language = "en"
multilingual = false
src = "src"
title = "bpf-developer-tutorial"

[output.linkcheck]
follow-web-links = true

exclude = [ 'openai.com', 'geekbang.org', 'aliyun.com' ]
